name = "Benchmarks"
uuid = "477c2568-c4f8-4ad5-9005-667adb27add6"
authors = ["kjxymful <pleibersperger@yahoo.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
